### PR TITLE
Fixed error setting and retaining OriginAccessIdentity in update_config_x

### PR DESCRIPTION
**Pull request by benlumley**
Fixed error setting and retaining OriginAccessIdentity in update_config_xml, was inserting to wrong point in XML, should be under S3Origin and not in the root of the body.

Issue as reported here: https://forums.aws.amazon.com/thread.jspa?threadID=60989

### CODE REVIEW

**Comment by skyzyx** [comment]
@benlumley: The AWS SDK for PHP is licensed under the Apache 2.0 license. Would you be willing to release this contribution under the same licensing terms?

**Comment by benlumley** [comment]
Yes, confirm I am happy to contribute this under the apache 2.0 license.

**Comment by skyzyx** [comment]
Sweet. Thanks!

**Comment by skyzyx** [comment]
This has gone live in 1.4.8.

**Pull request closed without merging**
