### PR TITLE
XML still being parsed when use_cache_flow is false

### PR DESCRIPTION
**Pull request by ecaron**
The fix that was introduced in 1.4.8 only worked when $this->use_cache_flow was true. Now $this->parse_the_response is checked in both places where $this->parse_callback may be called.

### CODE REVIEW

**Comment by skyzyx** [comment]
Reviewing the patch with relevant teams inside of Amazon.

The AWS SDK for PHP is licensed under the [Apache 2.0 license](http://opensource.org/licenses/Apache-2.0). Would you be willing to license this patch under the same legal terms?

**Comment by ecaron** [comment]
Absolutely. Is written confirmation enough or is there some other process I
need to follow? I would like to make sure all of my future patches are seen
as Apache 2 licensed to help speed things along too.

**Comment by skyzyx** [comment]
Just ensure that you specify that you release your changes under the Apache 2.0 license in your pull request.

**Comment by skyzyx** [comment]
I've pulled this patch into our internal source tree. The fix will go out with an upcoming release.

Thanks for the contribution! :)

**Pull request closed without merging**
